/**
 * نصوص صفحة التسعير بلغاتها — مفصولة عن PricingPage.tsx كي يستوردها اختبار حارس الادّعاءات
 * (src/content/claimsGuard.test.ts) **بالنص المشحون نفسه**: كان الاختبار يلصق نسخة يدوية من
 * صندوق الإنصاف، فلو عاد نفيٌ قديم هنا لنجح npm test ونجح البناء معاً (verify-claims لا يرى حزم JS،
 * وprerender يصيّر /pricing من نصوصه الخاصة).
 */
export type PricingLang = 'ar' | 'en' | 'fr';

export const PRICING_TEXT: Record<PricingLang, Record<string, string>> = {
  ar: {
    back: 'الرئيسية',
    title: 'أسعار Field Sales معلنة وبلا رسوم خفية',
    sub: 'السعر لكل شركة لا لكل مستخدم إضافة مندوب ضمن حد باقتك لا تزيد فاتورتك',
    perCompany: 'لكل شركة لا لكل مستخدم',
    noSetup: 'بلا رسوم تأسيس أو إعداد',
    vatIncl: 'شامل ضريبة القيمة المضافة',
    noCommit: 'بلا التزام سنوي',
    trial: 'تجربة ١٠ أيام بلا بطاقة ائتمان',
    talk: 'تحدث معنا على واتساب',
    startTrial: 'ابدأ التجربة المجانية',
    calcTitle: 'احسب الفرق بين نموذجي التسعير',
    calcSub: 'أغلب البدائل تسعر لكل مندوب أدخل عدد مناديبك وقارن الفاتورة السنوية',
    reps: 'عدد المناديب',
    perUserPrice: 'سعر المندوب الواحد شهريا لدى البديل ر.س',
    setupFee: 'رسوم تأسيس لمرة واحدة لدى البديل ر.س',
    vat: 'ضريبة القيمة المضافة %',
    ourModel: 'نموذجنا لكل شركة',
    theirModel: 'النموذج الشائع لكل مندوب',
    year1: 'إجمالي السنة الأولى',
    monthly: 'شهريا',
    save: 'الفرق في السنة الأولى',
    calcNote: 'الأرقام التي تدخلها افتراضاتك أنت لا نذكر اسم أي مورد هنا ولا نقدر سعرا لمن لا يعلنه',
    overLimit: 'فوق ٢٠ مندوبا نحدد السعر بالمحادثة حسب حجمك لا رقم معلن نخترعه',
    faqTitle: 'أسئلة عن التسعير',
    fairTitle: 'ما نملكه وما لا نملكه بصراحة',
    fairBody: 'ندعم الفاتورة الإلكترونية برمز QR وندعم **ربط المرحلة الثانية** مع منصة فاتورة التابعة لهيئة الزكاة والضريبة والجمارك والهيئة لا تعتمد ولا تصادق مزودي البرمجيات فلا ندعي اعتمادا منها وليست لدينا شهادات SOC2 أو ISO',
  },
  en: {
    back: 'Home',
    title: 'Field Sales pricing published with no hidden fees',
    sub: 'Priced per company not per user Adding a rep within your plan limit does not raise your bill',
    perCompany: 'Per company not per user',
    vatIncl: 'VAT included',
    noSetup: 'No setup or onboarding fees',
    noCommit: 'No annual lock-in',
    trial: '10-day trial no credit card',
    talk: 'Talk to us on WhatsApp',
    startTrial: 'Start the free trial',
    calcTitle: 'Compare the two pricing models',
    calcSub: 'Most alternatives charge per rep Enter your team size and compare the first-year bill',
    reps: 'Number of reps',
    perUserPrice: 'Alternative price per rep per month SAR',
    setupFee: 'One-off setup fee at the alternative SAR',
    vat: 'VAT %',
    ourModel: 'Our model per company',
    theirModel: 'Common model per rep',
    year1: 'First-year total',
    monthly: 'monthly',
    save: 'First-year difference',
    calcNote: 'The figures you enter are your own assumptions We name no vendor here and never estimate a price for one who does not publish it',
    overLimit: 'Above 20 reps we set the price in conversation based on your size we do not invent a published number',
    faqTitle: 'Pricing questions',
    fairTitle: 'What we have and do not have plainly',
    fairBody: 'We support **Phase 2 integration** with the Fatoora platform of ZATCA ZATCA does not certify or approve software vendors so we claim no approval from it We hold no SOC2 or ISO certification',
  },
  fr: {
    back: 'Accueil',
    title: 'Tarifs Field Sales publiés sans frais cachés',
    sub: 'Par entreprise pas par utilisateur Ajouter un commercial dans la limite de votre offre n augmente pas la facture',
    perCompany: 'Par entreprise pas par utilisateur',
    vatIncl: 'TVA incluse',
    noSetup: 'Aucuns frais de mise en service',
    noCommit: 'Sans engagement annuel',
    trial: 'Essai 10 jours sans carte',
    talk: 'Discutez avec nous sur WhatsApp',
    startTrial: 'Démarrer l essai gratuit',
    calcTitle: 'Comparez les deux modèles tarifaires',
    calcSub: 'La plupart des alternatives facturent par commercial Entrez la taille de votre équipe',
    reps: 'Nombre de commerciaux',
    perUserPrice: 'Prix par commercial et par mois chez l alternative SAR',
    setupFee: 'Frais de mise en service uniques SAR',
    vat: 'TVA %',
    ourModel: 'Notre modèle par entreprise',
    theirModel: 'Modèle courant par commercial',
    year1: 'Total première année',
    monthly: 'par mois',
    save: 'Écart sur la première année',
    calcNote: 'Les chiffres saisis sont vos propres hypothèses Nous ne nommons aucun fournisseur ici',
    overLimit: 'Au-delà de 20 commerciaux le prix se définit en conversation nous n inventons aucun chiffre publié',
    faqTitle: 'Questions sur les tarifs',
    fairTitle: 'Ce que nous avons et n avons pas clairement',
    fairBody: 'Nous prenons en charge **l intégration phase 2** avec la plateforme Fatoora de la ZATCA La ZATCA ne certifie aucun éditeur nous ne revendiquons donc aucune homologation',
  },
};
